# for travis-ci
# see also. https://travis-ci.org
language: php
sudo: required
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  fast_finish: true
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver currently unsupported by HHVM
  allow_failures:
    - php: hhvm
    - php: 7.0

env:
  - DB=mysql USER=root DBNAME=myapp_test DBPASS=' ' DBUSER=root
  - DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres

before_script:
  #- composer self-update
  - composer install --dev --no-interaction -o
  - sh -c "if [ '$DB' = 'mysql' ]; then sh ./eccube_install.sh mysql none; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sh ./eccube_install.sh pgsql none; fi"

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
