parameters:
    # EC-CUBE default env parameters
    env(ECCUBE_ADMIN_ROUTE): 'admin'
    env(ECCUBE_ADMIN_ALLOW_HOSTS): []
    env(ECCUBE_FORCE_SSL): false
    env(ECCUBE_TEMPLATE_CODE): 'default'

    # EC-CUBE parameters
    eccube_admin_route: '%env(ECCUBE_ADMIN_ROUTE)%'
    eccube_admin_allow_hosts: '%env(json:ECCUBE_ADMIN_ALLOW_HOSTS)%'
    eccube_force_ssl: '%env(bool:ECCUBE_FORCE_SSL)%'
    eccube.theme: '%env(ECCUBE_TEMPLATE_CODE)%'
    eccube_theme_code: '%eccube.theme%'
    auth_type: HMAC
    eccube_csv_size: 5                 # post_max_size, upload_max_filesize に任せればよい？
    eccube_csv_temp_realdir: '%kernel.cache_dir%/%kernel.environment%/eccube' # upload_tmp_dir に任せればよい？
    eccube_default_password: '**********'
    eccube_deliv_addr_max: 20
    eccube_deliv_date_end_max: 21
    eccube_id_max_len: 50
    eccube_id_min_len: 4
    eccube_int_len: 9                              # 最大値で制御したい
    eccube_category_nest_level: 5
    eccube_lltext_len: 99999
    eccube_ltext_len: 3000
    eccube_max_total_fee: 9999999999
    eccube_mltext_len: 1000
    eccube_mtext_len: 200
    plugin_html_realdir: /PATH/TO/WEB_ROOT/src/Eccube/Repository/Master/plugin/
    plugin_html_urlpath: /plugin/ # asset 使う
    plugin_realdir: /PATH/TO/WEB_ROOT/src/Eccube/Repository/Master/user_data/plugins/
    plugin_temp_realdir: /PATH/TO/WEB_ROOT/src/Eccube/Repository/Master/upload/temp_plugin/ # upload_tmp_dir に任せればよい？
    eccube_price_len: 8                                                    # 最大値で制御したい
    eccube_search_pmax: 10
    eccube_stext_len: 255
    eccube_sltext_len: 500
    eccube_smtext_len: 100
    eccube_tax_rule_priority: ['product_id','product_class_id','pref_id','country_id']
    eccube_url_len: 1024
    eccube_default_page_count: 10
    eccube_admin_product_stock_status: 3
    eccube_info_url: 'https://www.ec-cube.net/info/3/'
    eccube_customer_reset_expire: 10
    # CSVの区切り文字(タブ区切りにしたい場合は'\t'ではなく'    'で設定する
    eccube_csv_export_separator: ,
    # 出力エンコーディング
    eccube_csv_export_encoding: SJIS-win
    # 日付のフォーマット
    eccube_csv_export_date_format: 'Y-m-d H:i:s'
    # 複数データの区切り文字
    eccube_csv_export_multidata_separator: ,
    eccube_csv_import_delimiter: ,
    eccube_csv_import_enclosure: '"'
    eccube_csv_import_escape: \
    eccube_owners_store_url: https://www.ec-cube.net/upgrade/api/index.php
    eccube_name_len: 16
    eccube_kana_len: 25
    eccube_address1_len: 32
    eccube_address2_len: 32
    eccube_birth_max: 110
    eccube_product_order_price_lower: 1
    eccube_product_order_newer: 2
    eccube_product_order_price_higher: 3
    eccube_price_max: 2147483647
    eccube_tel_len: 5
    eccube_tel_len_min: 1
    eccube_zip01_len: 3
    eccube_zip02_len: 4
    eccube_password_min_len: 8
    eccube_password_max_len: 32
    auth_magic: '%env(ECCUBE_AUTH_MAGIC)%'
    password_hash_algos: SHA256
    eccube_composer_memory_limit: 1536
    eccube_order_mail_template_id: 1 #注文受付メール
    eccube_entry_confirm_mail_template_id: 2 #会員仮登録メール
    eccube_entry_complete_mail_template_id: 3 #会員本登録メール
    eccube_customer_withdraw_mail_template_id: 4 #会員退会メール
    eccube_contact_mail_template_id: 5 #問合受付メール
    eccube_forgot_mail_template_id: 6 #パスワードリセット
    eccube_reset_complete_mail_template_id: 7 #パスワードリマインダー