parameters:
    eccube_nav:
        product:
            name: admin.product.product_management
            icon: fa-cube
            children:
                product_master:
                    name: admin.product.product_list
                    url: admin_product
                product_edit:
                    name: admin.product.product_registration
                    url: admin_product_product_new
                class_name:
                    name: admin.product.class_management
                    url: admin_product_class_name
                class_category:
                    name: admin.product.category_management
                    url: admin_product_category
                product_tag:
                    name: admin.product.tag_management
                    url: admin_product_tag
                product_csv_import:
                    name: admin.product.product_csv_upload
                    url: admin_product_csv_import
                category_csv_import:
                    name: admin.product.category_csv_upload
                    url: admin_product_category_csv_import
        order:
            name: admin.order.order_management
            icon: fa-inbox
            children:
                order_master:
                    name: admin.order.order_list
                    url: admin_order
                order_edit:
                    name: admin.order.order_registration
                    url: admin_order_new
                shipping_csv_import:
                    name: admin.order.shipping_csv_upload
                    url: admin_shipping_csv_import
        customer:
            name: admin.customer.customer_management
            icon: fa-users
            children:
                customer_master:
                    name: admin.customer.customer_list
                    url: admin_customer
                customer_edit:
                    name: admin.customer.customer_registration
                    url: admin_customer_new
        content:
            name: admin.content.contents_management
            icon: fa-file-text-o
            children:
                news:
                    name: admin.content.news_management
                    url : admin_content_news
                file:
                    name: admin.content.file_management
                    url: admin_content_file
                layout:
                    name: admin.content.layout_management
                    url: admin_content_layout
                page:
                    name: admin.content.page_management
                    url: admin_content_page
                block:
                    name: admin.content.block_management
                    url: admin_content_block
                cache:
                    name: admin.content.cache_management
                    url: admin_content_cache
        setting:
            name: admin.setting
            icon: fa-cog
            children:
                shop:
                    name: admin.setting.shop
                    children:
                        shop_index:
                            name: admin.setting.shop.shop_setting
                            url: admin_setting_shop
                        shop_payment:
                            name: admin.nav.setting.shop.shop_payment
                            url: admin_setting_shop_payment
                        shop_delivery:
                            name: admin.nav.setting.shop.shop_delivery
                            url: admin_setting_shop_delivery
                        shop_tax:
                            name: admin.nav.setting.shop.shop_tax
                            url: admin_setting_shop_tax
                        shop_mail:
                            name: admin.nav.setting.shop.shop_mail
                            url: admin_setting_shop_mail
                        shop_csv:
                            name: admin.nav.setting.shop.shop_csv
                            url: admin_setting_shop_csv
                system:
                    name: admin.setting.system
                    children:
                        member:
                            name: admin.nav.setting.system.member
                            url: admin_setting_system_member
                        authority:
                            name: admin.nav.setting.system.authority
                            url: admin_setting_system_authority
                        security:
                            name: admin.nav.setting.system.security
                            url: admin_setting_system_security
                        log:
                            name: admin.setting.system.log_display
                            url: admin_setting_system_log
                        masterdata:
                            name: admin.setting.system.master_data_management
                            url: admin_setting_system_masterdata
                        system_index:
                            name: admin.setting.system.system_info
                            url: admin_setting_system_system
        store:
            name: admin.nav.store
            icon: fa-info-circle
            children:
                plugin:
                    name: admin.nav.store.plugin
                    children:
                        plugin_owners_search:
                            name: admin.nav.store.plugin.plugin_owners_install
                            url: admin_store_plugin_owners_search
                        plugin_list:
                            name: admin.nav.store.plugin.plugin_list
                            url: admin_store_plugin
                        plugin_handler:
                            name: admin.nav.store.plugin.plugin_handler
                            url: admin_store_plugin_handler
                template:
                    name: admin.nav.store.template
                    children:
                        template_list:
                            name: admin.nav.store.template.template_list
                            url: admin_store_template
                        template_install:
                            name: admin.nav.store.template.template_install
                            url: admin_store_template_install
                authentication_setting:
                    name: admin.nav.store.authentication_setting
                    url: admin_store_authentication_setting
