parameters:
  order_sattus:
    - &NEW '1'
    - &CANCEL '3'
    - &DELIVERED '5'
    - &PAID '6'
    - &IN_PROGRESS '9'
    - &RETURNED '10'

framework:
  workflows:
    order:
      type: 'state_machine'
      marking_store:
        type: 'single_state'
        arguments: 'OrderStatus.id'
      supports:
        - Eccube\Entity\Order
      initial_place: *NEW
      places:
        - *NEW
        - *PAID
        - *IN_PROGRESS
        - *CANCEL
        - *DELIVERED
        - *RETURNED
      transitions:
        pay:
          from: *NEW
          to: *PAID
        packing:
          from: [ *NEW, *PAID ]
          to: *IN_PROGRESS
        cancel:
          from: [ *NEW, *IN_PROGRESS ]
          to: *CANCEL
        back_to_in_progress:
          from: *CANCEL
          to: *IN_PROGRESS
        ship:
          from: [ *NEW, *PAID, *IN_PROGRESS ]
          to: *DELIVERED
        return:
          from: *DELIVERED
          to: *RETURNED
        cancel_return:
          from: *RETURNED
          to: *DELIVERED
