services:

    # Purchase Flow for Cart

    eccube.purchase.flow.cart:
        class: Eccube\Service\PurchaseFlow\PurchaseFlow
        calls:
            - [setItemHolderProcessors, ['@eccube.purchase.flow.cart.holder_processors']]
            - [setItemValidators, ['@eccube.purchase.flow.cart.item_validators']]
            - [setItemHolderValidators, ['@eccube.purchase.flow.cart.holder_validators']]

    eccube.purchase.flow.cart.holder_processors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\DeliveryFeeFreeProcessor'

    eccube.purchase.flow.cart.item_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\DisplayStatusValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\SaleLimitValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\DeliverySettingValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\StockValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\ProductStatusValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PriceChangeValidator'

    eccube.purchase.flow.cart.holder_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalLimitValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalNegativeValidator'

    # Purchase Flow for Shopping

    eccube.purchase.flow.shopping:
        class: Eccube\Service\PurchaseFlow\PurchaseFlow
        calls:
            - [setItemHolderProcessors, ['@eccube.purchase.flow.shopping.holder_processors']]
            - [setItemValidators, ['@eccube.purchase.flow.shopping.item_validators']]
            - [setItemHolderValidators, ['@eccube.purchase.flow.shopping.holder_validators']]
            - [setPurchaseProcessors, ['@eccube.purchase.flow.shopping.purchase']]

    eccube.purchase.flow.shopping.holder_processors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\DeliveryFeeProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\DeliveryFeeFreeByShippingProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\UsePointProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\AddPointProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\SubtractPointProcessor'

    eccube.purchase.flow.shopping.item_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\DisplayStatusValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\DeliverySettingValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\ProductStatusValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PriceChangeValidator'

    eccube.purchase.flow.shopping.holder_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\StockMultipleValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\SaleLimitMultipleValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalLimitValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalNegativeValidator'

    eccube.purchase.flow.shopping.purchase:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\OrderCodeProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\UsePointToCustomerPurchaseProcessor'

    # Purchase Flow for Order

    eccube.purchase.flow.order:
        class: Eccube\Service\PurchaseFlow\PurchaseFlow
        calls:
            - [setItemHolderProcessors, ['@eccube.purchase.flow.order.holder_processors']]
            - [setItemValidators, ['@eccube.purchase.flow.order.item_validators']]
            - [setItemHolderValidators, ['@eccube.purchase.flow.order.holder_validators']]
            - [setPurchaseProcessors, ['@eccube.purchase.flow.order.purchase']]

    eccube.purchase.flow.order.holder_processors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\UpdateDatePurchaseProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\UsePointProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\AddPointProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\SubtractPointProcessor'

    eccube.purchase.flow.order.item_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\StockValidator'

    eccube.purchase.flow.order.holder_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalLimitValidator'

    eccube.purchase.flow.order.purchase:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\AdminOrderRegisterPurchaseProcessor'
