twig:
    globals:
      BaseInfo: null
      eccube:
        config: '%eccube.constants%'
    paths:
      '%eccube.theme.front_dir%': ~
      '%eccube.theme.front_default_dir%': ~
      '%kernel.project_dir%/app/Plugin': ~
      '%eccube.theme.admin_dir%': admin
      '%eccube.theme.admin_default_dir%': admin
      '%eccube.theme.user_data_dir%': user_data
      '%eccube.theme.src_dir%/toolbar': toolbar
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # form_themes:
    #     - 'default_frame.twig'
    #     - 'Form/form_div_layout.twig'
