twig:
    paths: ['%kernel.project_dir%/src/Eccube/Resource/template/default']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
